name: CD
 
on:
  workflow_dispatch:    
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0

      - name: version installed
      - run: mvn -v
